version: "3.9"

services:
  postgres:
    image: postgres:15
    shm_size: "2048mb"
    volumes:
      - odoo_database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    ports:
      - "127.0.0.1:5438:5432"
    networks:
      - odoo_backend

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - odoo_data:/home/odoo
      - ../workspace:/workspace
    environment:
      - PGPASSWORD=odoo
      - PGUSER=odoo
      - PGHOST=postgres
      # Mail settings for Mailpit
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
    depends_on:
      - postgres
    ports:
      - "8018:8069"
      - "8048:8072"
    networks:
      - odoo_backend

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"  # SMTP server port
      - "8025:8025"  # Web interface port
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=true
      - MP_SMTP_AUTH_ALLOW_INSECURE=true
    networks:
      - odoo_backend

networks:
  odoo_backend:
    driver: bridge

volumes:
  odoo_database:
  odoo_data:
